### ISSUE TITLE
VS Can't pull/push- Not me being dumb.

### ISSUE THREAD

**Issue by NoiseGener8r** [armedturret/BLURF-Z-for-Zachariah#4]
W**e**lp.
Commit is gr**e**y**e**d out.
And wh**e**n I pull, it says 'pull r**e**qu**e**st fail**e**d'.

**Comment by armedturret** [comment]
You're dumb, pull request means that integration into the main project. Go to sync instead. *Slaps forehead*

**Comment by NoiseGener8r** [comment]
I did. I told you this already.

-Andrew

**Comment by armedturret** [comment]
CLICK ON PULL IN SYNC. YOUR CLICKING ON PULL REQUEST IF IT SAYS PULL REQUEST FAILS. Other than that, you need to fix merge conflicts (google it). The software works fine.
